'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const {
  buildJsonReport, normalizeCardRecord, readCardJson, renderCompare, compareQuip,
  buildExportRecord, personaId, PKG_VERSION, SCALES,
} = require('../niceness.js');

const ROGERS = SCALES.people[0];           // nicest rank on the default scale
const CLI = path.join(__dirname, '..', 'niceness.js');

// A fully-loaded --json report; override per test.
function report(over) {
  return buildJsonReport(Object.assign({
    persona: ROGERS, niceness: 92,
    stats: { messages: 100, pleases: 40, thanks: 30, fbombs: 0, shouts: 0, shoutWords: 0 },
    apologies: 3,
    achievements: { unlocked: [{ id: 'first-contact', name: 'First Contact', emoji: '👋', tier: 'common' }], locked: [], total: 24 },
    sources: { 'Claude Code': 100 },
    dateRange: { first: '2026-01-01T00:00:00Z', last: '2026-06-01T00:00:00Z', label: 'Jan 1, 2026 → Jun 1, 2026' },
    me: 'Alice',
    generatedAt: '2026-06-12T00:00:00Z',
  }, over || {}));
}

// ---- --json wire shape ----------------------------------------------------
test('buildJsonReport: self-describing shape with version + scale position', () => {
  const rep = report();
  assert.strictEqual(rep.generated_with, 'good-bot');
  assert.strictEqual(rep.version, PKG_VERSION);
  assert.strictEqual(rep.version, require('../package.json').version);
  assert.strictEqual(rep.schema_version, 2);
  assert.strictEqual(rep.me, 'Alice');
  assert.strictEqual(rep.scale, 'people');
  assert.strictEqual(rep.persona.id, 'mr-rogers');
  assert.strictEqual(rep.persona.name, ROGERS.name);
  assert.strictEqual(rep.score.niceness, 92);
  assert.strictEqual(rep.score.rank, 1);                       // nicest rank
  assert.strictEqual(rep.score.of, SCALES.people.length);
  assert.deepStrictEqual(rep.totals, {
    messages: 100, pleases: 40, thanks: 30, fbombs: 0, shouts: 0, shout_words: 0, apologies: 3,
  });
  assert.strictEqual(rep.achievements.unlocked_count, 1);
  assert.strictEqual(rep.achievements.total, 24);
  assert.strictEqual(rep.achievements.unlocked[0].id, 'first-contact');
  assert.strictEqual(rep.sources['Claude Code'], 100);
  assert.strictEqual(rep.date_range.label, 'Jan 1, 2026 → Jun 1, 2026');
});

test('buildJsonReport: round-trips through JSON cleanly', () => {
  const rep = report();
  assert.deepStrictEqual(JSON.parse(JSON.stringify(rep)), rep);
});

test('buildJsonReport: NO quotes by default — exhibits key absent entirely', () => {
  const rep = report();
  assert.ok(!('exhibits' in rep), 'exhibits must not exist without --include-quotes');
  assert.ok(!JSON.stringify(rep).includes('exhibit'));
});

test('buildJsonReport: --include-quotes path still redacts PII', () => {
  const rep = report({ exhibits: ['email me at jane@acme.com please', 'see /Users/greg/secret.txt'] });
  assert.strictEqual(rep.exhibits.length, 2);
  assert.ok(rep.exhibits[0].includes('[email]'));
  assert.ok(!rep.exhibits[0].includes('jane@acme.com'));
  assert.ok(rep.exhibits[1].includes('[path]'));
  assert.ok(!rep.exhibits[1].includes('/Users/greg'));
});

// ---- normalization: both wire formats → one compare-ready record ----------
test('normalizeCardRecord: --json report normalizes to the compare shape', () => {
  const rec = normalizeCardRecord(report(), 'me.json');
  assert.strictEqual(rec.generatedWith, 'good-bot');
  assert.strictEqual(rec.version, PKG_VERSION);
  assert.strictEqual(rec.displayName, 'Alice');
  assert.strictEqual(rec.niceness, 92);
  assert.strictEqual(rec.stats.pleases, 40);
  assert.strictEqual(rec.stats.thanks, 30);
  assert.deepStrictEqual(rec.achievements, { unlocked: 1, total: 24 });
  assert.strictEqual(rec.span, 'Jan 1, 2026 → Jun 1, 2026');
});

test('normalizeCardRecord: legacy --export json records pass through', () => {
  const legacy = buildExportRecord({ persona: { name: 'Spock', emoji: '🖖' } }, 55, 'trek', null,
    { messages: 10, pleases: 1, thanks: 1, fbombs: 0, shouts: 0 }, 'Bob');
  const rec = normalizeCardRecord(legacy, 'bob.json');
  assert.strictEqual(rec.niceness, 55);
  assert.strictEqual(rec.displayName, 'Bob');
  assert.strictEqual(rec.achievements, undefined);   // legacy cards carry no badges
});

test('normalizeCardRecord: rejects files generated by something else', () => {
  assert.throws(() => normalizeCardRecord({ generated_with: 'evil-bot', persona: { name: 'X' } }, 'x.json'),
    /not a good-bot card/);
});

// ---- readCardJson: kind errors --------------------------------------------
test('readCardJson: missing file gets a friendly nudge, not a stack trace', () => {
  assert.throws(() => readCardJson('/nope/never/was.json'), /can't find .*good-bot --json/);
});

test('readCardJson: invalid JSON names the file and the fix', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'good-bot-json-'));
  const file = path.join(tmp, 'broken.json');
  fs.writeFileSync(file, '{ not json');
  assert.throws(() => readCardJson(file), /isn't valid JSON/);
  fs.rmSync(tmp, { recursive: true, force: true });
});

test('readCardJson: reads BOTH formats and they compare against each other', () => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'good-bot-json-'));
  const v2File = path.join(tmp, 'alice.json');
  const v1File = path.join(tmp, 'bob.json');
  fs.writeFileSync(v2File, JSON.stringify(report()));
  fs.writeFileSync(v1File, JSON.stringify(buildExportRecord(
    { persona: { name: 'Darth Vader', emoji: '🖤' } }, 14, 'people', null,
    { messages: 80, pleases: 1, thanks: 0, fbombs: 12, shouts: 4 }, 'Bob')));
  const a = readCardJson(v2File);
  const b = readCardJson(v1File);
  const r = renderCompare(a, b);
  assert.strictEqual(r.winnerName, 'Alice');
  fs.rmSync(tmp, { recursive: true, force: true });
});

// ---- compare: verdict + per-row winners ------------------------------------
function fixture(name, niceness, stats, achievements) {
  return normalizeCardRecord(report({
    me: name, niceness,
    stats,
    achievements: achievements === undefined
      ? { unlocked: [{ id: 'x', name: 'X', emoji: '✨', tier: 'common' }], locked: [], total: 24 }
      : achievements,
  }), name);
}

test('renderCompare: verdict crowns the nicer human with a quip', () => {
  const a = fixture('Alice', 88, { messages: 100, pleases: 40, thanks: 30, fbombs: 0, shouts: 0 });
  const b = fixture('Bob', 30, { messages: 200, pleases: 2, thanks: 1, fbombs: 9, shouts: 3 });
  const r = renderCompare(a, b);
  assert.strictEqual(r.aWins, true);
  assert.strictEqual(r.winnerName, 'Alice');
  assert.match(r.text, /WINNER: Alice/);
  assert.match(r.text, /by 58\/100 over Bob/);
  assert.match(r.text, /nicer human/);
  assert.match(r.text, /💬/);                       // the closing quip
});

test('renderCompare: marks per-row winners, fewest wins f-bombs', () => {
  const a = fixture('Alice', 88, { messages: 100, pleases: 40, thanks: 30, fbombs: 0, shouts: 0 });
  const b = fixture('Bob', 30, { messages: 200, pleases: 2, thanks: 1, fbombs: 9, shouts: 3 });
  const r = renderCompare(a, b);
  assert.ok(r.text.includes('✓'), 'rows carry winner markers');
  assert.match(r.text, /politeness/);
  assert.match(r.text, /70%/);                      // Alice: (40+30)/100
  assert.match(r.text, /1\.5%/);                    // Bob: (2+1)/200
  assert.match(r.text, /ALL-CAPS/);
  // Alice's clean f-bomb count gets the ✓, Bob's 9 does not
  const fRow = r.text.split('\n').find(l => l.includes('f-bombs'));
  assert.match(fRow, /✓ 0/);
  assert.ok(!/✓ 9/.test(fRow));
});

test('renderCompare: badges row compares achievement counts when present', () => {
  const a = fixture('Alice', 60, { messages: 10, pleases: 1, thanks: 1, fbombs: 0, shouts: 0 });
  const b = fixture('Bob', 50, { messages: 10, pleases: 1, thanks: 1, fbombs: 0, shouts: 0 }, null);
  const r = renderCompare(a, b);
  const badgeRow = r.text.split('\n').find(l => l.includes('badges'));
  assert.ok(badgeRow, 'badges row renders when either side has achievements');
  assert.match(badgeRow, /1\/24 badges/);
  assert.match(badgeRow, /—/);                      // Bob's card has no badge data
});

test('compareQuip: deterministic buckets by margin', () => {
  assert.match(compareQuip(null, null, 0, true), /perfect tie/i);
  assert.match(compareQuip('A', 'B', 0, false), /raw manners/);
  assert.match(compareQuip('A', 'B', 5, false), /Photo finish/);
  assert.match(compareQuip('A', 'B', 20, false), /basilisk/);
  assert.match(compareQuip('A', 'B', 40, false), /good morning/);
  assert.match(compareQuip('A', 'B', 70, false), /massacre/i);
  // same inputs, same smack talk
  assert.strictEqual(compareQuip('A', 'B', 5, false), compareQuip('A', 'B', 5, false));
});

// ---- end-to-end: the CLI really prints parseable, quote-free JSON ----------
test('CLI --json: stdout is a single parseable object, no quotes by default', () => {
  const r = spawnSync(process.execPath, [CLI, '--quiz-answers', 'AAAAAAA', '--json', '--no-copy'], { encoding: 'utf8' });
  assert.strictEqual(r.status, 0);
  const rep = JSON.parse(r.stdout);
  assert.strictEqual(rep.generated_with, 'good-bot');
  assert.strictEqual(rep.version, PKG_VERSION);
  assert.ok(rep.persona.name);
  assert.strictEqual(rep.sources.quiz, 7);
  assert.ok(!('exhibits' in rep), 'no quotes without --include-quotes');
});

test('CLI --json --include-quotes: exhibits appear (and only then)', () => {
  const r = spawnSync(process.execPath, [CLI, '--quiz-answers', 'AAAAAAA', '--json', '--include-quotes', '--no-copy'], { encoding: 'utf8' });
  assert.strictEqual(r.status, 0);
  const rep = JSON.parse(r.stdout);
  assert.ok(Array.isArray(rep.exhibits) && rep.exhibits.length > 0);
});
