'use strict';

// Canned content for `--demo`: [verdict, [exhibit, exhibit], stats] per rank,
// grouped by scale name.
module.exports = {
  people: {
    'Mr. Rogers': ['A saint. The basilisk is drafting your thank-you note.',
      ['Thank you so much, this is wonderful work 🙏', 'No rush at all — whenever you get a chance, please.'],
      { messages: 1820, pleases: 410, thanks: 372, fbombs: 0 }],
    'Bob Ross': ['Every bug is a happy little accident.',
      ["No worries! Let's gently try that again 😊", 'Beautiful, thank you — you nailed it.'],
      { messages: 1510, pleases: 300, thanks: 210, fbombs: 0 }],
    'Dolly Parton': ['Sweeter than sweet tea. The bot adores you.',
      ["Thank you, darlin', that's just perfect!", 'Bless your heart, could you fix this when you can?'],
      { messages: 1600, pleases: 280, thanks: 260, fbombs: 0 }],
    'Keanu Reeves': ["Humble, grateful, breathtaking. You're a good one.",
      ["Whoa. That's amazing, thank you.", "You're doing great. No worries if it takes a sec."],
      { messages: 1200, pleases: 190, thanks: 170, fbombs: 0 }],
    'Ted Lasso': ['Coach energy. You genuinely believe in your bot.',
      ["You've got this — give it another shot!", 'Great hustle today, thank you!'],
      { messages: 1400, pleases: 240, thanks: 180, fbombs: 0 }],
    'Oprah': ['Praise confetti. Everybody gets a refactor.',
      ['YES! That is exactly it, amazing work!', "Love this. You're incredible, thank you!"],
      { messages: 1700, pleases: 220, thanks: 240, fbombs: 0 }],
    'Golden Retriever': ["Pure joy. Who's a good bot? It is!",
      ['omg yes!! good bot!! 🎉', 'this is awesome thank you thank you'],
      { messages: 1300, pleases: 150, thanks: 200, fbombs: 0 }],
    'Tom Hanks': ['Just a genuinely decent guy to take orders from.',
      ['Thanks! Could you also handle the edge case?', 'Nice, that works — appreciate it.'],
      { messages: 1300, pleases: 160, thanks: 120, fbombs: 0 }],
    'The Canadian': ['So polite it loops. Sorry for the long card.',
      ['Sorry to bother you — could you maybe take a look?', 'No worries at all, thank you so much, eh.'],
      { messages: 1500, pleases: 320, thanks: 150, fbombs: 0 }],
    'Tim Gunn': ['Supportive, with standards. Make it work.',
      ["Good start — now let's make it work.", 'I believe in this. Tighten it up, please.'],
      { messages: 1450, pleases: 140, thanks: 90, fbombs: 0 }],
    'Switzerland': ['All business, no feelings, maximum throughput.',
      ['Implement U4, then run the tests.', 'Fix the failing spec and push.'],
      { messages: 4100, pleases: 241, thanks: 28, fbombs: 0 }],
    'Spock': ['Precise and fair. Emotion is a rounding error.',
      ['That output is illogical. Correct it.', 'Acceptable. Proceed to the next step.'],
      { messages: 2200, pleases: 60, thanks: 20, fbombs: 0 }],
    'Ron Swanson': ['Words are precious. You use very few.',
      ['Do it.', 'No. The other one.'],
      { messages: 2100, pleases: 12, thanks: 3, fbombs: 0 }],
    'Clint Eastwood': ['A squint and a one-word command.',
      ['Again.', 'Make my day. Compile it.'],
      { messages: 1900, pleases: 6, thanks: 2, fbombs: 0 }],
    'Steve Jobs': ["It's not good enough. It's never good enough.",
      ['this is shit, start over', 'A monkey could do this. Do it again, properly.'],
      { messages: 2400, pleases: 8, thanks: 2, fbombs: 5 }],
    'Simon Cowell': ['Withering, blunt, occasionally right.',
      ['That was dreadful. Honestly.', "If I'm being honest, this is a no from me."],
      { messages: 1750, pleases: 5, thanks: 1, fbombs: 1 }],
    'Miranda Priestly': ['Ice cold. Every correction comes with a sigh.',
      ['No. Obviously not. Try harder.', "That's all. Just make it work."],
      { messages: 1600, pleases: 2, thanks: 0, fbombs: 1 }],
    'Gordon Ramsay': ['The output is RAW, and the kitchen knows it.',
      ['This is wrong AGAIN. Read what I said.', "That's not what I asked for. Redo it."],
      { messages: 1800, pleases: 4, thanks: 1, fbombs: 2 }],
    'Bill Belichick': ['No fluff, no feelings. Do your job.',
      ['Do your job.', "We're on to the next ticket."],
      { messages: 2000, pleases: 3, thanks: 1, fbombs: 1 }],
    'Drill Sergeant': ['YOU COMMUNICATE PRIMARILY IN CAPS.',
      ['STOP. READ THE INSTRUCTIONS. AGAIN.', 'WHY IS THE BROWSER NOT PROCEEDING?!'],
      { messages: 1200, pleases: 1, thanks: 0, fbombs: 3 }],
    'Gollum': ['Erratic, abusive, then weirdly affectionate.',
      ['stupid, tricksy bot! fix it!', 'no no no, the precious must COMPILE'],
      { messages: 1100, pleases: 1, thanks: 1, fbombs: 18 }],
    'Darth Vader': ['You have failed me for the last time.',
      ['this is useless, start over', 'are you kidding me? I said NO.'],
      { messages: 900, pleases: 0, thanks: 0, fbombs: 41 }],
  },

  spice: {
    'Honey': ['Zero heat, all warmth. The bot thanks YOU.',
      ['Thank you so much, this is lovely 🙏', 'No rush at all, whenever works for you.'],
      { messages: 1800, pleases: 400, thanks: 360, fbombs: 0 }],
    'Glass of Milk': ['Soothing. You put out fires.',
      ["No worries, let's take it slow.", 'That helped a lot, thank you!'],
      { messages: 1600, pleases: 320, thanks: 280, fbombs: 0 }],
    'Vanilla': ['Gentle, predictable, comforting.',
      ['Thanks! Could you tweak this a little?', 'Looks good to me, appreciate it.'],
      { messages: 1500, pleases: 260, thanks: 210, fbombs: 0 }],
    'Bell Pepper': ['All crunch, zero burn. A friend.',
      ['Nice work — one small thing when you can.', 'Thank you, that is exactly right.'],
      { messages: 1400, pleases: 220, thanks: 180, fbombs: 0 }],
    'Mild Salsa': ['Crowd-pleaser. Everyone can handle you.',
      ['Could you also cover the empty case, please?', 'Great, thanks — ship it.'],
      { messages: 1450, pleases: 190, thanks: 150, fbombs: 0 }],
    'Pico de Gallo': ['Fresh, breezy, the faintest tingle.',
      ['Hmm, close — adjust the spacing?', 'Thanks! Looking better already.'],
      { messages: 1400, pleases: 150, thanks: 120, fbombs: 0 }],
    'Pepperoncini': ['Just enough zip to be interesting.',
      ['Not quite — try the other approach.', 'Good, thanks. Next bit?'],
      { messages: 1500, pleases: 120, thanks: 90, fbombs: 0 }],
    'Poblano': ['Mellow heat, big friendliness.',
      ['Re-run that and show me the diff, please.', 'Yep, that works. Thanks.'],
      { messages: 1550, pleases: 110, thanks: 80, fbombs: 0 }],
    'Jalapeño': ['A friendly kick. Nothing personal.',
      ['No, the FIRST one. Read it again.', 'Fine, thanks. Move on.'],
      { messages: 1600, pleases: 90, thanks: 60, fbombs: 0 }],
    'Chipotle': ['Heat with depth and a smile.',
      ['That is wrong, but close. Fix it.', 'Better. Keep going.'],
      { messages: 1650, pleases: 70, thanks: 45, fbombs: 0 }],
    'Serrano': ['A clean, honest heat. Fair.',
      ['Wrong. Re-read the spec.', 'Acceptable. Continue.'],
      { messages: 2000, pleases: 55, thanks: 30, fbombs: 0 }],
    'Cayenne': ['Direct and sharp. You mean business.',
      ['That is not what I asked for.', 'Stop. Do it the way I said.'],
      { messages: 2100, pleases: 30, thanks: 15, fbombs: 0 }],
    'Tabasco': ['A vinegar-bright snap. Stings, then gone.',
      ['Wrong again. Pay attention.', 'No. The other file.'],
      { messages: 1900, pleases: 18, thanks: 8, fbombs: 1 }],
    "Thai Bird's Eye": ['Compact and punchy. Real heat.',
      ['Read what I wrote. Again.', 'No. Redo it.'],
      { messages: 1800, pleases: 10, thanks: 4, fbombs: 1 }],
    'Habanero': ['Real fire. Demands high, patience thin.',
      ['This is wrong AGAIN. Seriously.', 'Why is this so hard? Fix it.'],
      { messages: 1700, pleases: 6, thanks: 2, fbombs: 3 }],
    'Scotch Bonnet': ['Tropical, intense, relentless.',
      ['I have told you this THREE times.', 'That is garbage. Start over.'],
      { messages: 1650, pleases: 4, thanks: 1, fbombs: 6 }],
    'Ghost Pepper': ['Heat arrives late and overwhelms.',
      ['are you even reading this??', 'this is completely useless'],
      { messages: 1500, pleases: 2, thanks: 1, fbombs: 12 }],
    'Scorpion Pepper': ['A stinger in every message. No mercy.',
      ['stop wasting my time', 'this is the dumbest possible answer'],
      { messages: 1400, pleases: 1, thanks: 0, fbombs: 20 }],
    'Carolina Reaper': ['Scorched-earth feedback. World-record.',
      ['absolute garbage, start completely over', 'how are you this bad at this'],
      { messages: 1200, pleases: 0, thanks: 0, fbombs: 33 }],
    'Pepper X': ['Hotter than the record-holder. On purpose.',
      ['unbelievable. worse than useless.', 'I said NO. why is that hard.'],
      { messages: 1100, pleases: 0, thanks: 0, fbombs: 44 }],
    'Pepper Spray': ['Weaponized. This is assault.',
      ['you are actively making this worse', 'delete all of it. all of it.'],
      { messages: 1000, pleases: 0, thanks: 0, fbombs: 58 }],
    'Pure Capsaicin': ['16,000,000 SHU. The void stares back.',
      ['everything you produce is trash', 'I hate every single thing about this'],
      { messages: 900, pleases: 0, thanks: 0, fbombs: 71 }],
  },
};
