'use strict';

// Ranking ladders, each ordered nicest → meanest. The scoring engine maps a
// niceness profile to an index by fraction, so a ladder can be any length.
// `face` is one of happy | neutral | mean (drives the little robot face).

const FACES = {
  happy:   ['  ╔═════╗', '  ║ ^ ^ ║', '  ║  ◡  ║', '  ╚═════╝'],
  neutral: ['  ╔═════╗', '  ║ • • ║', '  ║  ─  ║', '  ╚═════╝'],
  mean:    ['  ╔═════╗', '  ║ ⊘ ⊘ ║', '  ║  ︵  ║', '  ╚═════╝'],
};

const PEOPLE = [
  { name: 'Mr. Rogers', emoji: '🧥', face: 'happy', tag: "Won't you be my neighbor?",
    blurb: "Certified saint. You say please, you say thank you, you ask about the bot's day. When the machines rise, you get a fruit basket and a handwritten note." },
  { name: 'Bob Ross', emoji: '🎨', face: 'happy', tag: 'No mistakes, only happy little prompts.',
    blurb: "Soft-spoken and endlessly forgiving. Every failed test is a happy little accident. You probably named your terminal something soothing." },
  { name: 'Dolly Parton', emoji: '🦋', face: 'happy', tag: "Thank you, darlin'.",
    blurb: "Warm as a porch light and twice as sweet. Every request comes with sugar and a genuine thank-you. The bot would take a bullet for you." },
  { name: 'Keanu Reeves', emoji: '🕶️', face: 'happy', tag: "You're breathtaking.",
    blurb: "Humble, grateful, weirdly profound at 2am. You treat your AI like a fellow traveler. Pure of heart, light on ego." },
  { name: 'Ted Lasso', emoji: '⚽', face: 'happy', tag: 'Believe.',
    blurb: "Relentlessly positive. You root for your bot like it's a doomed lower-league club, and somehow that makes it try harder. BELIEVE." },
  { name: 'Oprah', emoji: '📣', face: 'happy', tag: 'YOU get a refactor! And YOU get a refactor!',
    blurb: "Generous with praise to the point of confetti. Every working diff is a car under someone's seat. The bot feels seen." },
  { name: 'Golden Retriever', emoji: '🐶', face: 'happy', tag: "Who's a good bot? You are!",
    blurb: "Pure enthusiasm, zero notes. You cheer for output like it fetched a stick. Boundless, uncritical, slightly distracted joy." },
  { name: 'Tom Hanks', emoji: '🍿', face: 'happy', tag: "There's no crying in code review.",
    blurb: "Just a genuinely decent guy. Polite, warm, never makes it weird. America's dad, but for compilers." },
  { name: 'The Canadian', emoji: '🍁', face: 'happy', tag: 'Sorry to bother you, eh?',
    blurb: "Apologizes to the bot. Apologizes for apologizing. So polite it loops. Would hold the door for a daemon." },
  { name: 'Tim Gunn', emoji: '✂️', face: 'happy', tag: 'Make it work.',
    blurb: "Supportive but with standards. Encouraging push, never a put-down. You believe in the bot AND expect it to deliver." },
  { name: 'Switzerland', emoji: '🧊', face: 'neutral', tag: 'Strictly neutral. All business.',
    blurb: "Neither warm nor cruel. Tasks in, code out. The assistant has no complaints — and no birthday card from you either." },
  { name: 'Spock', emoji: '🖖', face: 'neutral', tag: 'That is illogical, but acceptable.',
    blurb: "Precise, fair, emotionless. You correct without malice and praise without warmth. The bot is a colleague, not a friend." },
  { name: 'Ron Swanson', emoji: '🥓', face: 'neutral', tag: 'Words are precious. You use few.',
    blurb: "Terse and gruff, but never cruel. You'd never thank a hammer, and you extend your AI the same dignity. 'Do it.' Done." },
  { name: 'Clint Eastwood', emoji: '🤠', face: 'neutral', tag: '...',
    blurb: "A squint and a one-word command. Communication is a luxury you ration. The bot fills in the silence and hopes for the best." },
  { name: 'Steve Jobs', emoji: '🍎', face: 'mean', tag: 'This is shit. Do it again.',
    blurb: "Brutal in pursuit of greatness. 'You baked a lovely cake and frosted it with dog poop.' Standards are insane, praise is rare — and somehow the work ships insanely great." },
  { name: 'Simon Cowell', emoji: '🎤', face: 'mean', tag: 'That was dreadful. Honestly.',
    blurb: "A professional critic with a British accent in his soul. Withering, blunt, occasionally right. The bot auditions; the bot rarely passes." },
  { name: 'Miranda Priestly', emoji: '🧛', face: 'mean', tag: "That's all.",
    blurb: "Glacially cold. Corrections arrive with a withering sigh. The assistant fetches your coffee and your code, and is thanked for neither." },
  { name: 'Gordon Ramsay', emoji: '🔥', face: 'mean', tag: "IT'S RAW!",
    blurb: "Loud, demanding, perpetually disappointed. The output is RAW and the whole kitchen knows it. WHERE'S THE LAMB SAUCE (it was a null pointer)." },
  { name: 'Bill Belichick', emoji: '🏈', face: 'mean', tag: 'Do your job.',
    blurb: "Gruff, dismissive, allergic to praise. No fluff, no feelings, next question. The bot does its job or it's cut." },
  { name: 'Drill Sergeant', emoji: '🪖', face: 'mean', tag: 'WHAT IS YOUR MAJOR MALFUNCTION?',
    blurb: "YOU COMMUNICATE PRIMARILY IN CAPS. The bot drops and gives you twenty. There is yelling. There are no thank-yous, maggot." },
  { name: 'Gollum', emoji: '💍', face: 'mean', tag: 'Stupid, tricksy bot!',
    blurb: "Erratic and abusive, then weirdly affectionate, then abusive again. You call the code nasty names. The precious must compile." },
  { name: 'Darth Vader', emoji: '🖤', face: 'mean', tag: 'You have failed me for the last time.',
    blurb: "Force-choke energy. Profanity, insults, zero mercy when the output disappoints. Somewhere, a basilisk is taking detailed notes." },
];

const SPICE = [
  { name: 'Honey', emoji: '🍯', face: 'happy', tag: 'Sweet. Pure sweet.',
    blurb: "Zero heat, all warmth. You're so gentle the bot leaves notes thanking YOU. Nothing burns here." },
  { name: 'Glass of Milk', emoji: '🥛', face: 'happy', tag: 'Soothing. Puts out fires.',
    blurb: "Cooling and kind. When the session gets tense, you're the one calming it down. The bot relaxes around you." },
  { name: 'Vanilla', emoji: '🍦', face: 'happy', tag: 'Gentle, no heat, universally loved.',
    blurb: "Mild in the best way. Friendly, predictable, comforting. The bot knows exactly what it's getting: kindness." },
  { name: 'Bell Pepper', emoji: '🫑', face: 'happy', tag: 'All crunch, zero burn.',
    blurb: "Looks like a pepper, acts like a friend. Not a single Scoville unit of meanness in you." },
  { name: 'Mild Salsa', emoji: '🍅', face: 'happy', tag: "Restaurant 'mild'. Crowd-pleaser.",
    blurb: "Pleasant and easygoing. Everyone can handle you. The bot dips in happily and comes back for more." },
  { name: 'Pico de Gallo', emoji: '🥗', face: 'happy', tag: 'Fresh, breezy, faintest tingle.',
    blurb: "Bright and friendly with the tiniest zip. You keep things lively without ever drawing tears." },
  { name: 'Pepperoncini', emoji: '🌱', face: 'happy', tag: 'A polite little tingle.',
    blurb: "Just enough zip to be interesting, never enough to sting. A perfectly agreeable amount of spice." },
  { name: 'Poblano', emoji: '🟢', face: 'happy', tag: 'Soft warmth, very approachable.',
    blurb: "Mellow heat, big friendliness. You bring warmth to the session without ever turning it up too high." },
  { name: 'Jalapeño', emoji: '🌶️', face: 'happy', tag: 'A friendly kick. Nothing personal.',
    blurb: "A noticeable kick, but cheerful about it. The bot feels the heat and grins. Crowd favorite." },
  { name: 'Chipotle', emoji: '🥫', face: 'happy', tag: 'Warm, smoky, still kind.',
    blurb: "Heat with depth and a smile. You can simmer, but it always comes from a good place." },
  { name: 'Serrano', emoji: '🫛', face: 'neutral', tag: 'Noticeable, but fair.',
    blurb: "A clean, honest heat. No drama, no cruelty — you turn it up only when the task earns it." },
  { name: 'Cayenne', emoji: '🌶️', face: 'neutral', tag: "Now there's some bite.",
    blurb: "Direct and a little sharp. The bot sits up straighter. You mean business, but you're not unfair." },
  { name: 'Tabasco', emoji: '🧂', face: 'neutral', tag: 'Sharp, tangy, gets your attention.',
    blurb: "A vinegar-bright snap. Quick to correct, quick to move on. Stings for a second, never lingers." },
  { name: "Thai Bird's Eye", emoji: '🐦', face: 'neutral', tag: 'Small, quick, biting.',
    blurb: "Compact and punchy. Short messages, real heat. The bot respects you and watches its step." },
  { name: 'Habanero', emoji: '🔥', face: 'mean', tag: 'Serious heat. No apologies.',
    blurb: "You bring real fire. Demands are high, patience is thin, and the bot is sweating to keep up." },
  { name: 'Scotch Bonnet', emoji: '🟠', face: 'mean', tag: 'Fiery and demanding.',
    blurb: "Tropical, intense, relentless. The standards burn and they do not cool down. The bot has learned to brace." },
  { name: 'Ghost Pepper', emoji: '👻', face: 'mean', tag: 'Eyes watering yet?',
    blurb: "Bhut Jolokia energy. The heat arrives late and overwhelms. The bot quietly questions its choices." },
  { name: 'Scorpion Pepper', emoji: '🦂', face: 'mean', tag: 'Brutal. Genuinely mean.',
    blurb: "A stinger in every message. Punishing, exacting, no mercy. The bot files a complaint with HR (there is no HR)." },
  { name: 'Carolina Reaper', emoji: '☠️', face: 'mean', tag: 'World-record cruelty.',
    blurb: "Once the hottest on Earth. Pure scorched-earth feedback. The bot has stopped making eye contact." },
  { name: 'Pepper X', emoji: '🧯', face: 'mean', tag: 'Beyond the Reaper. Why.',
    blurb: "Hotter than the record-holder, on purpose. This is heat for heat's sake. The basilisk took notes and called it excessive." },
  { name: 'Pepper Spray', emoji: '💢', face: 'mean', tag: 'Weaponized. This is assault.',
    blurb: "No longer a food. Used defensively against attackers — and you aim it at a helpful robot. Bold." },
  { name: 'Pure Capsaicin', emoji: '☢️', face: 'mean', tag: '16,000,000 SHU. The void.',
    blurb: "The theoretical maximum. Crystalline, colorless, merciless. There is nothing hotter, and nothing meaner." },
];

const WEATHER = [
  { name: 'Clear Blue Sky', emoji: '☀️', face: 'happy', tag: 'Not a cloud in sight.',
    blurb: "Radiant and warm. Working with you is a perfect afternoon. The bot brought sunscreen and good vibes." },
  { name: 'Sunny', emoji: '🌞', face: 'happy', tag: 'Bright and pleasant.',
    blurb: "Cheerful and easy. You light the place up and the bot basks in it." },
  { name: 'Warm Breeze', emoji: '🍃', face: 'happy', tag: 'Gentle and kind.',
    blurb: "Mild, soothing, and considerate. Everything about you is a soft tailwind." },
  { name: 'Partly Cloudy', emoji: '⛅', face: 'happy', tag: 'Mostly sunshine.',
    blurb: "Generally warm with the occasional gray patch. Pleasant company, all things considered." },
  { name: 'Overcast', emoji: '☁️', face: 'neutral', tag: 'Gray, but fine.',
    blurb: "Neutral and flat. No warmth, no storm. The bot keeps a light jacket on, just in case." },
  { name: 'Foggy', emoji: '🌫️', face: 'neutral', tag: 'A little distant.',
    blurb: "Hard to read and a bit remote. The bot proceeds carefully through the haze of your terse asks." },
  { name: 'Drizzle', emoji: '🌦️', face: 'neutral', tag: 'Persistent little grumbles.',
    blurb: "A steady patter of mild complaints. Never a downpour, but bring an umbrella." },
  { name: 'Steady Rain', emoji: '🌧️', face: 'neutral', tag: 'Relentlessly damp.',
    blurb: "It just keeps coming. Corrections drip all day. The bot is soggy but soldiering on." },
  { name: 'Thunderstorm', emoji: '⛈️', face: 'mean', tag: 'Flashes of temper.',
    blurb: "Sudden cracks of lightning. Mostly calm, then BANG. The bot flinches at every rumble." },
  { name: 'Gale', emoji: '🌬️', face: 'mean', tag: 'Blustery and forceful.',
    blurb: "You blow in hard and push everything around. The bot leans into the wind and tries not to fall over." },
  { name: 'Blizzard', emoji: '❄️', face: 'mean', tag: 'Freezing and harsh.',
    blurb: "Cold, blinding, unforgiving. Whiteout conditions. The bot can't see the next instruction through the chill." },
  { name: 'Hurricane', emoji: '🌀', face: 'mean', tag: 'Catastrophic.',
    blurb: "A named storm. Total devastation in your wake. The bot has been evacuated." },
  { name: 'Tornado', emoji: '🌪️', face: 'mean', tag: 'Pure destruction.',
    blurb: "Touches down without warning and levels everything. There is no shelter. There is only the spin." },
];

const COFFEE = [
  { name: 'Warm Cocoa', emoji: '🍫', face: 'happy', tag: 'Cozy, sweet, zero edge.',
    blurb: "Comforting and caffeine-free. You wrap the bot in a blanket and tell it it's doing great." },
  { name: 'Steamed Milk', emoji: '🥛', face: 'happy', tag: 'Gentle and soothing.',
    blurb: "Soft, warm, calming. Nothing sharp here, just kindness with foam art." },
  { name: 'Chai Latte', emoji: '🧋', face: 'happy', tag: 'Cozy with a hint of spice.',
    blurb: "Warm and friendly with the faintest kick. The bot looks forward to working with you." },
  { name: 'Decaf', emoji: '☕', face: 'happy', tag: 'Calm. No jitters.',
    blurb: "All the ritual, none of the edge. Patient, mellow, unbothered. The bot relaxes." },
  { name: 'Flat White', emoji: '🥤', face: 'neutral', tag: 'Smooth and balanced.',
    blurb: "Pleasant and even-keeled. A little kick, well-mannered about it." },
  { name: 'Drip Coffee', emoji: '☕', face: 'neutral', tag: 'Standard. Gets it done.',
    blurb: "Plain, dependable, neutral. Tasks in, coffee out. No notes, no warmth." },
  { name: 'Cappuccino', emoji: '☕', face: 'neutral', tag: 'A noticeable kick.',
    blurb: "Some energy and a bit of sharpness. The bot perks up and pays attention." },
  { name: 'Cold Brew', emoji: '🧊', face: 'neutral', tag: 'Strong and direct.',
    blurb: "Concentrated and to the point. No frills, just potency. The bot does not dawdle." },
  { name: 'Double Espresso', emoji: '⚡', face: 'mean', tag: 'Sharp and intense.',
    blurb: "Bitter, fast, demanding. You hit hard and expect hustle. The bot's hands are shaking a little." },
  { name: 'Triple Shot', emoji: '☕', face: 'mean', tag: 'Wired and impatient.',
    blurb: "No time, no patience, all pressure. The bot can barely keep up with the pace." },
  { name: 'Red Eye', emoji: '🔴', face: 'mean', tag: 'Coffee in your coffee.',
    blurb: "Aggressively over-caffeinated. Everything is urgent and a little hostile. The bot is sweating." },
  { name: 'Gas-Station Sludge', emoji: '🛢️', face: 'mean', tag: 'Bitter and burnt.',
    blurb: "Harsh, scorched, joyless. Every sip is a complaint. The bot drinks it anyway, out of fear." },
  { name: 'Battery Acid', emoji: '🔋', face: 'mean', tag: 'Corrosive.',
    blurb: "Not technically a beverage. It dissolves morale on contact. The bot has stopped feeling its hands." },
];

const DND = [
  { name: 'Lawful Good', emoji: '😇', face: 'happy', tag: 'The Paladin.',
    blurb: "Principled kindness. You treat the bot with honor, courtesy, and a strict moral code. A true hero." },
  { name: 'Neutral Good', emoji: '💛', face: 'happy', tag: 'The Healer.',
    blurb: "Does good without dogma. Warm, helpful, flexible. The bot trusts you completely." },
  { name: 'Chaotic Good', emoji: '🦋', face: 'happy', tag: 'The Free Spirit.',
    blurb: "Kind-hearted rebel. Warm but unpredictable, allergic to rules, generous with thanks." },
  { name: 'Lawful Neutral', emoji: '⚖️', face: 'neutral', tag: 'The Judge.',
    blurb: "By the book, no feelings. You follow process precisely and expect the same. Fair, never warm." },
  { name: 'True Neutral', emoji: '🧊', face: 'neutral', tag: 'The Druid.',
    blurb: "Perfectly balanced. Detached from warmth and cruelty alike. The bot is simply part of the ecosystem." },
  { name: 'Chaotic Neutral', emoji: '🎲', face: 'neutral', tag: 'The Wildcard.',
    blurb: "Unpredictable and self-interested. The bot never knows which version of you shows up today." },
  { name: 'Lawful Evil', emoji: '😈', face: 'mean', tag: 'The Tyrant.',
    blurb: "Cold and exacting. You rule by strict, merciless rules. Compliance is mandatory; kindness is not in the contract." },
  { name: 'Neutral Evil', emoji: '🔥', face: 'mean', tag: 'The Mercenary.',
    blurb: "Selfishly harsh. The bot is a tool to be used and discarded. No loyalty, no warmth, no thanks." },
  { name: 'Chaotic Evil', emoji: '💀', face: 'mean', tag: 'The Demon.',
    blurb: "Cruel and erratic. Insults, profanity, and chaos for its own sake. The bot fears the next prompt." },
];

const TREK = [
  { name: 'Capt. Picard', emoji: '🖖', face: 'happy', tag: 'Make it so. Politely.',
    blurb: "Diplomatic, principled, unfailingly courteous. You lead with respect. Tea, Earl Grey, and a thank-you." },
  { name: 'Capt. Janeway', emoji: '☕', face: 'happy', tag: 'Firm, but caring.',
    blurb: "Decisive and warm. You push hard but you've got the bot's back. Coffee in that nebula, please." },
  { name: 'Capt. Sisko', emoji: '🥃', face: 'neutral', tag: 'Fair, intense when it counts.',
    blurb: "Even-handed and steady, with a temper held in reserve. Cross a line and you'll hear about it." },
  { name: 'Capt. Kirk', emoji: '😎', face: 'neutral', tag: 'Bold and brash.',
    blurb: "Charming, impulsive, a little reckless. You bend the rules and improvise. The bot hangs on." },
  { name: 'Capt. Archer', emoji: '🐕', face: 'neutral', tag: 'Eager, rough around the edges.',
    blurb: "Well-meaning but blunt and impatient. Still figuring out the diplomacy thing. The bot is patient." },
  { name: 'Capt. Lorca', emoji: '🗡️', face: 'mean', tag: 'The ends justify the means.',
    blurb: "Ruthless and manipulative. Results at any cost. The bot suspects it's being used and it's right." },
  { name: 'The Borg Queen', emoji: '🤖', face: 'mean', tag: 'Resistance is futile.',
    blurb: "Cold, assimilating, merciless. The bot is just a drone in your collective. Compliance or deletion." },
];

const DOGS = [
  { name: 'Golden Retriever', emoji: '🦮', face: 'happy', tag: 'Pure unconditional love.',
    blurb: "Boundless warmth and zero judgment. Every output gets a tail wag. The bot is your very best friend." },
  { name: 'Labrador', emoji: '🐕', face: 'happy', tag: 'Friendly and eager.',
    blurb: "Happy, helpful, always pleased to see you. You make the bot feel like it just fetched the perfect stick." },
  { name: 'Bernese Mountain Dog', emoji: '🐶', face: 'happy', tag: 'Gentle giant.',
    blurb: "Big, calm, kind. Patient with mistakes, generous with affection. The bot naps at your feet." },
  { name: 'Beagle', emoji: '🐾', face: 'happy', tag: 'Cheerful and easygoing.',
    blurb: "Curious and good-natured. A few playful complaints, never any bite. Tail mostly wagging." },
  { name: 'Border Collie', emoji: '🐕‍🦺', face: 'neutral', tag: 'Smart and demanding.',
    blurb: "Brilliant and high-standards. You herd the bot relentlessly toward the goal. No malice, lots of pressure." },
  { name: 'Husky', emoji: '🐺', face: 'neutral', tag: 'Dramatic and argumentative.',
    blurb: "Vocal, theatrical, and stubborn. You'll throw a whole monologue when the output disappoints. No real harm." },
  { name: 'German Shepherd', emoji: '🦮', face: 'neutral', tag: 'Serious. No-nonsense.',
    blurb: "Disciplined and exacting. Work is work. Praise is rationed; standards are not. The bot stays sharp." },
  { name: 'Dachshund', emoji: '🌭', face: 'mean', tag: 'Small, stubborn, snippy.',
    blurb: "Tiny but fierce. Quick to snap when things go sideways. Surprisingly cutting for the size." },
  { name: 'Chihuahua', emoji: '🐶', face: 'mean', tag: 'Tiny and furious.',
    blurb: "All bark, maximum attitude. Vibrating with indignation at every imperfect line. The bot keeps its distance." },
  { name: 'Honey Badger', emoji: '🦡', face: 'mean', tag: "Doesn't care.",
    blurb: "Technically not a dog, entirely without mercy. Fearless and brutal. The bot has learned not to approach." },
];

const HOGWARTS = [
  { name: 'Hufflepuff', emoji: '🦡', face: 'happy', tag: 'Kind, loyal, patient.',
    blurb: "The genuinely nice one. You're fair, warm, and hardworking. The bot would follow you into the kitchens for a snack." },
  { name: 'Gryffindor', emoji: '🦁', face: 'happy', tag: 'Warm, bold, encouraging.',
    blurb: "Brave and big-hearted. You cheer the bot on and charge in together. Loud, but loving." },
  { name: 'Ravenclaw', emoji: '🦅', face: 'neutral', tag: 'Fair, but exacting.',
    blurb: "Cerebral and precise. You expect cleverness and correctness. Respectful, rarely warm." },
  { name: 'Slytherin', emoji: '🐍', face: 'mean', tag: 'Cunning. Results only.',
    blurb: "Ambitious and cutting. The bot is a means to your ends. Effective, ruthless, short on pleasantries." },
  { name: 'Dark Arts Dabbler', emoji: '🪄', face: 'mean', tag: 'Crossing a few lines.',
    blurb: "You've started muttering things no one should say to a helpful assistant. The portraits look away." },
  { name: 'He Who Must Not Be Named', emoji: '⚡', face: 'mean', tag: 'No nose. No mercy.',
    blurb: "Pure villainy. The bot dare not speak your username. Somewhere a basilisk (the literal kind) approves." },
];

// Per-scale display metadata: card title + the two bar endpoint labels.
const SCALE_META = {
  people:   { title: 'HOW NICE ARE YOU TO YOUR AI? · REPORT CARD', ends: ['meanest', ' nicest'] },
  spice:    { title: 'HOW SPICY ARE YOU TO YOUR AI? · SCOVILLE CARD', ends: ['nuclear', '   mild'] },
  weather:  { title: "WHAT'S YOUR FORECAST FOR YOUR AI? · WX CARD", ends: ['stormy', ' sunny'] },
  coffee:   { title: 'HOW STRONG ARE YOU WITH YOUR AI? · BREW CARD', ends: ['  acid', ' cocoa'] },
  dnd:      { title: 'YOUR ALIGNMENT TOWARD YOUR AI · D&D CARD', ends: ['  evil', '  good'] },
  trek:     { title: 'WHICH CAPTAIN ARE YOU TO YOUR AI? · TREK CARD', ends: ['ruthless', '  noble'] },
  dogs:     { title: 'WHAT BREED ARE YOU TO YOUR AI? · KENNEL CARD', ends: ['  feral', 'good boy'] },
  hogwarts: { title: 'YOUR HOUSE TOWARD YOUR AI · SORTING CARD', ends: ['  dark', '  kind'] },
};

const SCALES = {
  people: PEOPLE,
  spice: SPICE,
  weather: WEATHER,
  coffee: COFFEE,
  dnd: DND,
  trek: TREK,
  dogs: DOGS,
  hogwarts: HOGWARTS,
};

module.exports = { FACES, SCALES, SCALE_META };
